spring.application.name=poc-chat
server.port=8080

# configurations/Logging pour déboguer WebSocket
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG